import type { Metadata } from "next";
import localFont from "next/font/local";
import { Comfortaa } from 'next/font/google';
import "./globals.css";

const mainFont = Comfortaa({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${mainFont.className} antialiased bg-[#0d0c0d] text-[#e8e8df]`}
      >
        {children}
      </body>
    </html>
  );
}
